export const LOAD_ALL_USERS = "LOAD_ALL_USERS";
export const LOAD_ALL_USERS_COMPLETE = "LOAD_ALL_USERS_COMPLETE";
export const LOAD_ALL_USERS_ERROR = "LOAD_ALL_USERS_ERROR";

export const LOAD_USER = "LOAD_USER";
export const LOAD_USER_COMPLETE = "LOAD_USER_COMPLETE";
export const LOAD_USER_ERROR = "LOAD_USER_ERROR";